appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: PWGZIhSU/1NZO+R/SblJUZ1Ep0k6ZUxfLBQuecFXzPx1qV4Q19vTXCKK/SAvFogRwyxSzD53VTJ/QkpAUQ2GTh5mQOe1aswVC7ViCT+oKpAgwPeDU9GH3BN3hD2wJZowZzZ7/ypCSXAwE1McUh3IyTcE48NvixysnDXvSTvsElRy7p35u9HTHTqU+nOoIv32nf+qUe3MH2j9K4c4OjbzqEPYjzT2CWAca/1XNIOk9++zvI3q8m6lvT0f5mUlUUtR8Yn7O/1GCjaXY5fBMiBC40y6J8Z0lcpmAW7fFHc3ZRSCxS4utWfpVBG4dz4M+ilBg6lqqNAso4i48gfx4boPdbjLV+iDcoNuYTlunImbKlkEtvFqF0H1oUWaxpPhe9RF3qBxr/DuCaixmN5fMOfN8THy5TOJG5ve1IyhzOJWesXbG2OXrIvWR7dXXk4AQkmVbv/RpkJvZO+5yI9TgGVbRfJoejQppLYivCTjHuXPSs4Ky84OKOy2pk2e2CJWhky/S/4Af5XqfTAdMzxE+HuDDbzxpo8z3BPZilRShsXlOGKTWYt4YfWnSk6HiM5RExcwSjJuWH1SgVRnqZbYQ/U/xWVwDP+vYzRKWcf4rox8L+9gjwE1sB3FIvSD//15dNQUhI1VKS4/x2vFl4CvV/ZbpKxUsUJc2FQoBeOFopBj+N4=}
provider:
  win: azure
bot:
  automerge: true
